version: 2.1
jobs:
  build:
    build:
    parallelism: 10
    machine:
       image: ubuntu-2004:202101-01
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          pip install --upgrade pip
          chmod +x set-up.sh
          ./set-up.sh
